# Generated by Django 3.2.6 on 2022-01-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200, null=True)),
                ('Lastname', models.CharField(max_length=200, null=True)),
                ('Mothersname', models.CharField(max_length=200, null=True)),
                ('Fathersname', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=500, null=True)),
                ('Gender', models.CharField(max_length=2, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('DOB', models.CharField(max_length=200, null=True)),
                ('Pincode', models.CharField(max_length=200, null=True)),
                ('Course', models.CharField(max_length=200, null=True)),
                ('EmailId', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
